//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GenerateProcedures : DbContext
    {
        public GenerateProcedures()
            : base("name=GenerateProcedures")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Z_INSERT_MATRIKS_GAJI_IND_TEST(string pI_GRED, Nullable<decimal> pI_GAJI_MULA, ObjectParameter pI_BEZA, Nullable<decimal> pI_TAHAP, string pI_KOD_GAJI, Nullable<decimal> pI_PERINGKAT, ObjectParameter tAHAPMAX)
        {
            var pI_GREDParameter = pI_GRED != null ?
                new ObjectParameter("PI_GRED", pI_GRED) :
                new ObjectParameter("PI_GRED", typeof(string));
    
            var pI_GAJI_MULAParameter = pI_GAJI_MULA.HasValue ?
                new ObjectParameter("PI_GAJI_MULA", pI_GAJI_MULA) :
                new ObjectParameter("PI_GAJI_MULA", typeof(decimal));
    
            var pI_TAHAPParameter = pI_TAHAP.HasValue ?
                new ObjectParameter("PI_TAHAP", pI_TAHAP) :
                new ObjectParameter("PI_TAHAP", typeof(decimal));
    
            var pI_KOD_GAJIParameter = pI_KOD_GAJI != null ?
                new ObjectParameter("PI_KOD_GAJI", pI_KOD_GAJI) :
                new ObjectParameter("PI_KOD_GAJI", typeof(string));
    
            var pI_PERINGKATParameter = pI_PERINGKAT.HasValue ?
                new ObjectParameter("PI_PERINGKAT", pI_PERINGKAT) :
                new ObjectParameter("PI_PERINGKAT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Z_INSERT_MATRIKS_GAJI_IND_TEST", pI_GREDParameter, pI_GAJI_MULAParameter, pI_BEZA, pI_TAHAPParameter, pI_KOD_GAJIParameter, pI_PERINGKATParameter, tAHAPMAX);
        }
    }
}
